---
# 
platform: linux

inputs:
 - name: labbuildr-concourse-tasks
 - name: labbuildr-scripts
outputs:
 - name: node-state


params:
    GOVC_INSECURE: 
    GOVC_PASSWORD: 
    GOVC_URL: 
    GOVC_USERNAME: 
    GOVC_RESOURCE_POOL: 
    GOVC_DATASTORE: 
    GOVC_DATACENTER: 
    GOVC_NETWORK: 
    LABBUILDR_DATASTORE: 
    LABBUILDR_VM_FOLDER: 
    LABBUILDR_VM_NAME:
    LABBUILDR_DEVICE: cdrom-3000
    LABBUILDR_DEBUG:   
 
run:
  path: labbuildr-concourse-tasks/vsphere/scripts/generate-scripts-iso.sh

